### ISSUE TITLE
migrate to libcue2

### ISSUE THREAD

**Issue by Wang-Yue** [bsdelf/mous#2]
It fixes numerous problems (including pregap timing fix). 

Should be pretty straightforward. you can refer what I've done for cmus: https://github.com/cmus/cmus/commit/68d650c8fada236582a6c2fbc80d8dff065c630d

**Comment by bsdelf** [comment]
Thanks for the hint.
The migration has been finished:
cd607d2581c6e09bc019d9ca0bc5fc1f33b6c73a

**Comment by Wang-Yue** [comment]
Verified this builds with libcue 2.1. Closing this.
