### ISSUE TITLE
coreaudio backend

### ISSUE THREAD

**Issue by Wang-Yue** [bsdelf/mous#3]
libao is not under active development. It's mac output driver is outdated, and calls deprecated Carbon API. 

It's better to have a native CoreAudio plugin.  I've written one for CMUS: https://github.com/cmus/cmus/blob/master/coreaudio.c

I can relicense the file to you under BSDL. You won't need most part of it (output device selection, sample rate synchronization, device hogging code, channel mapping), so it should be trivial to convert that code to C++.

**Comment by bsdelf** [comment]
I do not want to convert that code into C++. Instead, I'm going to import the coreaudio related code from CMUS project directly and make as less patch as possible.

https://github.com/bsdelf/mous/commit/cb8e244e9f4c7d3e56080d6db3c6cefd1fa90369
