### ISSUE TITLE
cmake does not install plugins on Mac OS X

### ISSUE THREAD

**Issue by Wang-Yue** [bsdelf/mous#4]
I built it with flac and cue enabled. 

in Plugins directory I can see 
13:53:58 build $ ls plugins/
libCuePack.dylib	libTagLibParser.dylib	libWavEncoder.dylib
libFlacDecoder.dylib	libWavDecoder.dylib

However it does not install them to the location:

13:57:29 build $ make install
[  6%] Built target CuePack
[ 13%] Built target FlacDecoder
[ 31%] Built target MousCore
[ 40%] Built target TagLibParser
[ 47%] Built target WavDecoder
[ 54%] Built target WavEncoder
[ 68%] Built target mous-cli
[100%] Built target mous-ncurses
Install the project...
-- Install configuration: ""
-- Installing: /Users/wangyue/mous/lib/libMousCore.dylib
-- Installing: /Users/wangyue/mous/bin/mous-cli
-- Installing: /Users/wangyue/mous/bin/mous-ncurses

And as a result it cannot find plugins:

13:52:19 bin $ ./mous-cli plugin
need more plugins!
Decoders:   0
Endocers:   0
Renderers:  0
MediaPacks: 0
TagParsers: 0

**Comment by bsdelf** [comment]
Fix by commit https://github.com/bsdelf/mous/commit/635e85937971de3d6d6655d47f824fdc59de3a8f
